# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: room.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroom.proto\x12\x0broomPackage\"\x1b\n\rRoomIdRequest\x12\n\n\x02id\x18\x01 \x01(\x03\" \n\x0cRoomCapacity\x12\x10\n\x08\x63\x61pacity\x18\x01 \x01(\x05\x32N\n\x04Room\x12\x46\n\x0bGetCapacity\x12\x1a.roomPackage.RoomIdRequest\x1a\x19.roomPackage.RoomCapacity\"\x00\x62\x06proto3')



_ROOMIDREQUEST = DESCRIPTOR.message_types_by_name['RoomIdRequest']
_ROOMCAPACITY = DESCRIPTOR.message_types_by_name['RoomCapacity']
RoomIdRequest = _reflection.GeneratedProtocolMessageType('RoomIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _ROOMIDREQUEST,
  '__module__' : 'room_pb2'
  # @@protoc_insertion_point(class_scope:roomPackage.RoomIdRequest)
  })
_sym_db.RegisterMessage(RoomIdRequest)

RoomCapacity = _reflection.GeneratedProtocolMessageType('RoomCapacity', (_message.Message,), {
  'DESCRIPTOR' : _ROOMCAPACITY,
  '__module__' : 'room_pb2'
  # @@protoc_insertion_point(class_scope:roomPackage.RoomCapacity)
  })
_sym_db.RegisterMessage(RoomCapacity)

_ROOM = DESCRIPTOR.services_by_name['Room']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROOMIDREQUEST._serialized_start=27
  _ROOMIDREQUEST._serialized_end=54
  _ROOMCAPACITY._serialized_start=56
  _ROOMCAPACITY._serialized_end=88
  _ROOM._serialized_start=90
  _ROOM._serialized_end=168
# @@protoc_insertion_point(module_scope)
